server:
  port: 8002
spring:
  application:
    name: user-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fshy.management.userprovider.bean
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/
  instance:
    instance-id: provider2
    prefer-ip-address: true

