server:
  port: 6001
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/,http://eureka2.com:7002/eureka/
  instance:
    instance-id: gateway.com
    prefer-ip-address: true
zuul:
  routes:
    user:
      serviceId: user-provider
      path: /user/**
  ignored-services: user-provider
  prefix: /neu
