server:
  port: 8080
spring:
  application:
    name: feign
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka.com:7001/eureka/,http://eureka2.com:7002/eureka/
feign:
  hystrix:
    enabled: true